import React from "react";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const link =
    "https://brs.ecitizen.go.ke/backend/id-lookup?id_number=29216950&citizenship=citizen&first_name=kipyegon";

  const fetchuserInfo = async (id, fn) => {
    try {
      const user = await axios.get(
        `https://brs.ecitizen.go.ke/backend/id-lookup?id_number=${id}&citizenship=citizen&first_name=${fn}`
      );
      console.log(user);
    } catch (error) {
      console.log("brs err", error.message);
    }
  };
  React.useEffect(() => {
    fetchuserInfo(29216950, "Kipyegon");
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Next js </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
